function [r_val,c] = calc_weight2(f,z, y)
cnt1 =1;
%rc1 = 0;
rf = 0;
KNN = 0;
NO_OF_CLASS = length(unique(y));
distance = -100;
class_lbl = unique(y);
no_of_data = size(f,1); % check size 2/1
c=[];
y=z;
arr1= f(1:round(0.8*length(f)),:);
z = z(1:round(0.8*length(f)),:);
[rc1,K,zz] = subCalcWeight(arr1,f, z,y);
rf = rf+rc1;
rc1 = rc1/size(arr1,1);
KNN = KNN +size(arr1,1)*K;
c = [c ;zz];
%r_val = rf/(no_of_data*7);
r_val = rf;